server:
  port: 8080

spring:
  application:
    name: codechallange
  datasource:
    url: jdbc:mysql://localhost:3306/codechallange?createDatabaseIfNotExist:true
    username: root
    driverClassName: com.mysql.jdbc.Driver
    password: password
    validationQuery: SELECT 'x'
    validationInterval: 60000
    tomcat:
      max-active: 100
      max-wait: 10000
    jackson:
      serialization:
        fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true